### ISSUE TITLE
Allow specific struct fields to be ignored the the NBT decoder

### ISSUE THREAD

**Issue by ReCore-sys** [ferrumc-rs/ferrumc#11]
@Sweattypalms
A field attribute that allows the NBT system to not attempt to decode/encode and instead just use the `Default::default()` function for each field assuming that the type has the trait implemented.
For example
```rs
struct Example {
    #[nbt(ignore)]
    example_field: String
}
```
should produce something akin to
```rs
Example {
   example_field: String::default()
}
```
Would be really useful in the conversion process for chunks to denote fields that can be guaranteed to exist in the converted field but won't exist in the vanilla chunk, since currently I have to use a bunch of options which clutter it up a lot.
Will also be useful for reducing memory use since we can easily ignore fields we don't actually need without filling it all with comments.

**Comment by Sweattypalms** [comment]
I'll make a better NBT codec in the new version 🥲
