### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ReCore-sys** [ferrumc-rs/ferrumc#14]
Having a basic website would be cool, could help garner attention. Domain is already sorted, we just need something to point it at.

**Comment by ReCore-sys** [comment]
@CookieJul

**Comment by angusforrest** [comment]
Are you looking to host a static [github pages](https://pages.github.com/) landing page?
Attaching a custom url can be done and means there won't be server cost for hosting the website.

**Comment by ReCore-sys** [comment]
Some other guys are working out the website and their current plan seems to be using netlify or vercel

**Comment by cookiejul** [comment]
We have decided to use Astro + TailwindCSS for the frontend, and we will be hosting it on Netlify

**Comment by Sweattypalms** [comment]
Handled in the discord server (`#website-development` channel)
