### ISSUE TITLE
Evaluate using more optimizations like LTO and PGO

### ISSUE THREAD

**Issue by zamazan4ik** [ferrumc-rs/ferrumc#15]
Hi!

Just read a [post](https://www.reddit.com/r/rust/comments/1fcvyjb/ferrumc_an_actually_fast_minecraft_server/) about the project on Reddit - nice work! Since you aim to build a *fast* Minecraft server, I think I have several ideas to share about how possibly the project performance can be improved even further.

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit (in this case, it's not critical at all but anyway). According to my local quick tests on Linux, enabling LTO reduces the `ferrumc` binary size for Release mode from 8.3 Mib to 6 Mib size on the current `dev`'s HEAD commit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO also will be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO also should help).

Additionally to LTO, I can suggest evaluating for Ferrumc more advanced optimizations like Profile-Guided Optimization (PGO) and Post-Link Optimization (PLO). I have a lot of information (including a lot of benchmarks, including games!) in my repository: https://github.com/zamazan4ik/awesome-pgo . For playing with PGO I can recommend the [cargo-pgo](https://github.com/Kobzol/cargo-pgo) utility.

Thank you.

P.S. I created the Issue since Discussions are disabled for the repository. It's not a bug report - just an improvement idea.

**Comment by ReCore-sys** [comment]
Hey thanks for the feedback. I am planning on setting up another cargo profile to enable every optimisation (including targeting the native cpu) but adding lto is going to increase compile times too much if enabled by default. Will look into your other suggestions though.

**Comment by ReCore-sys** [comment]
Did some more research and while I do really appreciate the suggestions, this is probably not something we will be pursuing any time soon. People wanting the maximal possible performance out of a server can set up BOLT and such on their own. Trying to get a generic solution that works for everyone is going to be difficult and trying to have some sort of support going for an experimental LLVM optimization tool would be a major drain on resources. 
I may add a note or two about it for people to investigate on their own, but this is unlikely to be properly provided by us.
I am also of the opinion that trying to get tools like PGO working to optimize the final binary is going to produce much smaller boosts in performance than simply focusing on writing optimal code. PGO can't fix slow code, so focusing on that is not going to be the best use of our time.
Again, I really appreciate the advice and the time spent gathering those resources, but for the time being we'd rather focus on writing efficient code.
