### ISSUE TITLE
[Project] Migrate from binary to workspace and subcrates

### ISSUE THREAD

**Issue by Asurar0** [ferrumc-rs/ferrumc#16]
It's a common best practice in Rust to organize large projects into separate subcrates to mitigate the overhead of a single package. This approach can improve compilation speed, promote better code quality, modularity, and a more maintainable architecture. While consolidating code into a single crate may seem convenient, it can lead to a cluttered and unmaintainable codebase as the project grows.

[`Pumpkin`](https://github.com/Snowiiii/Pumpkin) have used this approach since the beginning.

**Comment by ReCore-sys** [comment]
We did try this originally (reverted here 80c4e6adb81b07a04678bc8d7febf9c0c0c4f477) but ran into many issues with circular imports. If we end up doing a major refactor at some point we may consider it, but for now the importing hellhole we had to dig ourselves out of before doesn't seem too appealing
