### ISSUE TITLE
Some unreasonable usages, gonna fix?

### ISSUE THREAD

**Issue by chanmaoganda** [ferrumc-rs/ferrumc#20]
## Repo contains many unresolved clippy lints
- `!opt.is_some()`, but `opt.is_none()` is better
- `&*ref_sth`, but auto deref is applied when passing only `&ref_sth`

## Besides, some function signature could be better
- passing a `Vec<u8>` as a argument, which in my opinion `&[u8]` is better
- ...

**Comment by ReCore-sys** [comment]
Neither of us use clippy for linting but I'll look into it

**Comment by Metaa4245** [comment]
> Neither of us use clippy for linting but I'll look into it

using clippy for linting is very beneficial, in my opinion it should be part of CI and maybe even done locally

**Comment by Sweattypalms** [comment]
We're using clippy and other useful things in the rewrite. Thanks for the advice.
