### ISSUE TITLE
Thread panic at LastChunkTxPos::distance_to

### ISSUE THREAD

**Issue by NKDark** [ferrumc-rs/ferrumc#23]
OS:
Windows 10 19045

Env:
```powershell
cargo --version
cargo 1.82.0-nightly (5f6b9a922 2024-07-19)
```
Screenshot:
![20240914-024539](https://github.com/user-attachments/assets/d6ef69b4-bff1-4bc7-ac08-2b88718e43e5)
![20240914-030626](https://github.com/user-attachments/assets/dd92b73a-04a0-4cfc-a24c-cc9d83b121bb)

**Comment by NKDark** [comment]
#22

**Comment by ReCore-sys** [comment]
Thanks for catching that, assuming the fix on your other pull requests works I'll merge that and close this one.
