### ISSUE TITLE
Requires nightly channel for build

### ISSUE THREAD

**Issue by talves** [ferrumc-rs/ferrumc#25]
When building from a clone, there is an error using the stable release. It requires nightly to be able to compile.

I propose using a `rust-toolchain.toml` config to target nightly.

Here is the error I received and using the config fixed it for me.
![image](https://github.com/user-attachments/assets/58b4dc3b-8a6c-4277-8fd1-7116d8f01e82)

**Comment by talves** [comment]
PR #22  has already been given. Not sure the other fix in that PR is needed, so let me know if you want a PR for just the config.

**Comment by ReCore-sys** [comment]
https://github.com/ferrumc-rs/ferrumc/pull/22
Fixed
