### ISSUE TITLE
Clean codebase and make workspace PLEASE

### ISSUE THREAD

**Issue by Asurar0** [ferrumc-rs/ferrumc#38]
Said by @Sweattypalms 
https://discord.com/channels/1277314213878173726/1284802381011357736/1284916402083463261

He finished the event system. So now cleanup is allowed.

If you subcrate all ferrumc, you won't only have my time and my energy. You'll have my loyalty.

**Comment by Rusty-Weasel** [comment]
:+1: Clean codebase and workspace PLEASE

**Comment by Sweattypalms** [comment]
yeah rewrite. https://github.com/sweattypalms/ferrumc/tree/rewrite/v3
