### ISSUE TITLE
failed to connect to the server

### ISSUE THREAD

**Issue by JeromeSchmied** [ferrumc-rs/ferrumc#63]
### Describe the Bug

Failed to connect to the server

Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:game_profile'

### To Reproduce

start the server, make direct connection to it from minecraft java edition

### Expected Behaviour

should connect and load the world

### Screenshots / Videos

not available

### FerrumC Version

github actions #102

### Rust Version

latest stable: rustc 1.81.0
host: x86_64-unknown-linux-gnu
LLVM version: 18.1.7

### Server Logs

[log](https://0x0.st/X6Dy.log)

### Additional Context

I just wanted to try using ferrumc (using TLauncher)
I checked all the boxes without reading them

### Is there an existing issue for this?

- [X] I have searched current existing issues before creating this.
- [X] I checked all the boxes without reading them
- [X] I have provided all necessary and relevant details, including logs, reproduction steps, etc.

**Comment by ReCore-sys** [comment]
We are currently working on a rewrite so any bug fixes are unlikely right now. However, we have had some issues in the past with other game clients so give it a try with the vanilla client if you can.

**Comment by JeromeSchmied** [comment]
it isn't really possible, but I'll just wait for the rewrite

**Comment by Skullians** [comment]
You are using the correct mc client ver right?

**Comment by JeromeSchmied** [comment]
well, sorry but I have no idea

**Comment by ReCore-sys** [comment]
it should be version 1.20.1

**Comment by Skullians** [comment]
> well, sorry but I have no idea

So you didn’t even know what client version you were trying to connect with?

**Comment by JeromeSchmied** [comment]
I knew it was the latest one, but wouldn't have thought it should matter
I'm no huge Minecraft fan
but it di
